version: 2

# Set default GitHub settings
repository:
  # Allow merge commits
  enable_merge_commits: true
  # Allow squash merging
  enable_squash_merging: true
  # Allow rebase merging
  enable_rebase_merging: true
  # Allow auto-merge
  enable_auto_merge: true
  # Delete branch after merge
  delete_branch_on_merge: true

# Set issue templates
issues:
  template_dir: .github/ISSUE_TEMPLATE

# Set pull request template
pull_requests:
  template_path: .github/PULL_REQUEST_TEMPLATE.md
