name: Branch Permission Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-branch-permissions:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch permissions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          ACTOR="${{ github.actor }}"
          REPO_OWNER="${{ github.repository_owner }}"

          echo "Checking permissions for branch: $BRANCH_NAME"
          echo "PR author: $ACTOR"

          # Check if user is an organization member
          MEMBERSHIP_STATUS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/orgs/$REPO_OWNER/members/$ACTOR" \
            -w "%{http_code}" -o /dev/null)

          IS_ORG_MEMBER=false
          if [ "$MEMBERSHIP_STATUS" = "204" ]; then
            IS_ORG_MEMBER=true
            echo "✅ User $ACTOR is an organization member"
          else
            echo "ℹ️ User $ACTOR is not an organization member (external contributor)"
          fi

          # Check if branch requires org membership
          REQUIRES_ORG_MEMBERSHIP=false
          if [[ $BRANCH_NAME =~ ^feature/ ]] || [[ $BRANCH_NAME =~ ^release/ ]] || [[ $BRANCH_NAME =~ ^chore/ ]] || [[ $BRANCH_NAME =~ ^hotfix/ ]]; then
            REQUIRES_ORG_MEMBERSHIP=true
          fi

          # Validate permissions
          if [ "$REQUIRES_ORG_MEMBERSHIP" = true ] && [ "$IS_ORG_MEMBER" = false ]; then
            echo "❌ ERROR: Branch '$BRANCH_NAME' can only be created by CometChat organization members."
            echo ""
            echo "📋 External contributors should use:"
            echo "- fix/ (for bug fixes, typos, broken links)"
            echo "- docs/ (for documentation improvements)"
            echo "- community/ (for examples, guides, general contributions)"
            echo ""
            echo "🔒 Organization members can use:"
            echo "- feature/ (for new product features)"
            echo "- release/ (for release preparation)"
            echo "- chore/ (for maintenance tasks, dependency updates)"
            echo "- hotfix/ (for critical production fixes)"
            echo ""
            echo "Please create a new branch with an appropriate prefix."
            exit 1
          else
            echo "✅ Branch permissions validated successfully"
          fi
